version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - nodeodm

  nodeodm:
    image: opendronemap/nodeodm
    ports:
      - "3000:3000"
    restart: always